services:

  - type: web

    name: chat-app-client

    env: static

    buildCommand: npm install && npm run build

    staticPublishPath: ./build

    headers:

      - source: /*

        headers:

          - key: Cache-Control

            value: no-cache 
